name: Proxy Scraper Checker

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest  # 选择在 Ubuntu 环境上运行

    steps:
    # 步骤 1：检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 步骤 5：运行 proxy-scraper-checker 脚本
    - name: Run Proxy Scraper Checker
      run: |
        # 确保 proxy-scraper-checker 可执行
        chmod +x ./proxy-scraper-checker
        ./proxy-scraper-checker  # 运行脚本，生成 out 文件夹

    # 步骤 6：将 out 文件夹上传到 GitHub 仓库
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        
        # 将 out 文件夹中的内容提交到仓库
        git add out/
        git commit -m "Update proxies output"
        git push origin main  # 推送到主分支
